#
# Copyright 2019 NXP
# Copyright 2026 MYIR
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += myd-js8mpq.o

ifdef CONFIG_XPL_BUILD
obj-y += spl.o
obj-$(CONFIG_IMX8M_LPDDR4) += lpddr4_timing.o
endif
