# SPDX-License-Identifier: GPL-2.0+
# (C) Copyright 2016 Freescale Semiconductor, Inc.

obj-y  := myd_imx6ull14x14.o

# Use MYIR vendor logo (tools/logos/myir.bmp) when building U-Boot for this board.
LOGO_BMP := $(srctree)/tools/logos/myir.bmp
